# Generated by Django 5.2.8 on 2025-12-03 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('dia', models.CharField(max_length=20)),
                ('inicio', models.TimeField()),
                ('fim', models.TimeField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.docente')),
            ],
        ),
    ]
